/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function listYk() {
    return invoke()<string[]>("list_yk")
}

export function selectYubikey(data: SelectedYubiKey) {
    return invoke()<null>("select_yubikey", { data })
}

export function verifyYubikeyPin(data: SelectedYubiKey) {
    return invoke()<null>("verify_yubikey_pin", { data })
}

export function initDatabase() {
    return invoke()<null>("init_database")
}

export function listDb() {
    return invoke()<MyFieldTs[]>("list_db")
}

export function addDbItem(data: MyFieldTs) {
    return invoke()<null>("add_db_item", { data })
}

export type SelectedYubiKey = { serial: string; pin: string }
export type MyFieldTs = { id: string | null; test_field: string }
